// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async getCurrentSsid(): Promise<string | null> {
    return await TAURI_INVOKE("plugin:location-connectivity|get_current_ssid");
  },
  async getTrustedSsids(): Promise<string[]> {
    return await TAURI_INVOKE("plugin:location-connectivity|get_trusted_ssids");
  },
  async addTrustedSsid(ssid: string): Promise<null> {
    return await TAURI_INVOKE("plugin:location-connectivity|add_trusted_ssid", {
      ssid,
    });
  },
  async removeTrustedSsid(ssid: string): Promise<null> {
    return await TAURI_INVOKE(
      "plugin:location-connectivity|remove_trusted_ssid",
      { ssid },
    );
  },
  async isLocationBasedEnabled(): Promise<boolean> {
    return await TAURI_INVOKE(
      "plugin:location-connectivity|is_location_based_enabled",
    );
  },
  async setLocationBasedEnabled(enabled: boolean): Promise<null> {
    return await TAURI_INVOKE(
      "plugin:location-connectivity|set_location_based_enabled",
      { enabled },
    );
  },
  async isInTrustedLocation(): Promise<boolean> {
    return await TAURI_INVOKE(
      "plugin:location-connectivity|is_in_trusted_location",
    );
  },
  async getLocationStatus(): Promise<LocationStatus> {
    return await TAURI_INVOKE(
      "plugin:location-connectivity|get_location_status",
    );
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type LocationStatus = {
  is_enabled: boolean;
  current_ssid: string | null;
  is_in_trusted_location: boolean;
  trusted_ssids: string[];
  should_use_cloud: boolean;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
